(function(){
   // var myApp = angular.module('myApp',["ngRoute"]);
    myApp.config(function($routeProvider){
        $routeProvider
            .when("/main",{
                templateUrl:"main.jsp",
                controller:"MainCtrl"
            })
            .when("/users",{
                templateUrl:"users.jsp",
                controller:"UserListCtrl"
            })
            .when("/customer",{
                templateUrl:"customer.jsp",
                controller:"CustomerCtrl"
            })
            .when("/company",{
                templateUrl:"company.jsp",
                controller:"companyCtrl"
            })
            .when("/farm",{
                templateUrl:"farm.jsp",
                controller:"farmCtrl"
            })
            .when("/product",{
                templateUrl:"product.jsp",
                controller:"productCtrl"
            })
            .when("/purchaseType",{
                templateUrl:"purchaseType.jsp",
                controller:"purchaseTypeCtrl"
            })
            .when("/purchase",{
                templateUrl:"purchase.jsp",
                controller:"purchaseCtrl"
            })
            .when("/tag",{
                templateUrl:"tag.jsp",
                controller:"tagCtrl"
            })
            .when("/animal",{
                templateUrl:"animal.jsp",
                controller:"animalCtrl"
            })
            .when("/feedUsed",{
                templateUrl:"feedUsed.jsp",
                controller:"feedUsedCtrl"
            })
            .when("/animalPrice",{
                templateUrl:"animalPrice.jsp",
                controller:"animalPriceCtrl"
            })
            .when("/purchaseDetail",{
                templateUrl:"purchaseDetail.jsp",
                controller:"purchaseDetailCtrl"
            })
            .when("/stock",{
                templateUrl:"stock.jsp",
                controller:"stockCtrl"
            })
            .when("/login",{
                templateUrl:"login.jsp",
                controller:"loginCtrl"
            })
            .otherwise({redirectTo:"/main"})
    })

}());